language: perl
# perl:
  # - "5.26-shrplib"
  # - "5.26"
sudo: true
dist: xenial
install:
  # - yes | perlbrew install-cpanm
  - git clone --branch=hack --depth=50 https://github.com/catb0t/sidef sidef
  # - git clone --branch=master --depth=50 https://github.com/trizen/sidef sidef
  - sudo apt update
  - yes | sudo apt install libmpfr-dev libmpc-dev libgmp10 libgmp3-dev
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm Log::Log4perl
  - cpanm forks JSON::XS Data::Dump::Filtered Algorithm::Combinatorics Algorithm::Loops Math::GMPq Math::GMPz Math::MPC Math::MPFR Math::Prime::Util Math::Prime::Util::GMP Math::BigInt::GMP Math::BigInt::Calc Math::BigInt::FastCalc

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780351
# https://rt.cpan.org/Public/Bug/Display.html?id=102730
# https://lists.freebsd.org/pipermail/freebsd-perl/2015-May/010803.html
  - chmod u+w /home/$USER/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/forks.pm
  - patch -p2 -F2 -u -i misc/forks.patch /home/$USER/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/forks.pm
  - perl -Mforks

script:
  - misc/test-sidef.sh sidef/bin/sidef sidefext/* lib/* providers/* tests/*
