language: perl
sudo: true
dist: xenial
install:
  - git clone https://github.com/trizen/sidef sidef
  - sudo apt update
  - yes | sudo apt install libmpfr-dev libmpc-dev libgmp10 libgmp3-dev
  - cpanm i Log::Log4perl Algorithm::Combinatorics Algorithm::Loops Math::GMPq Math::GMPz Math::MPC Math::MPFR Math::Prime::Util Math::Prime::Util::GMP Math::BigInt::GMP Math::BigInt::Calc Math::BigInt::FastCalc
script:
  - tests/test-sidef.sh sidef/bin/sidef lib/* providers/* tests/*
