language: perl
perl:
  - "5.26-shrplib"
  - "5.26"
sudo: true
dist: xenial
install:
  - git clone --branch=master --depth=50 https://github.com/trizen/sidef sidef
  - sudo apt update
  - yes | sudo apt install libmpfr-dev libmpc-dev libgmp10 libgmp3-dev
  - cpan --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpan forks JSON::XS Data::Dump::Filtered Log::Log4perl Algorithm::Combinatorics Algorithm::Loops Math::GMPq Math::GMPz Math::MPC Math::MPFR Math::Prime::Util Math::Prime::Util::GMP Math::BigInt::GMP Math::BigInt::Calc Math::BigInt::FastCalc
script:
  - misc/test-sidef.sh sidef/bin/sidef sidefext/* lib/* providers/* tests/*
